from .overlapadd_norm import LambdaOverlapAdd_norm
from .overlapadd_w2v import LambdaOverlapAdd_Wav2Vec
from .overlapadd_chunk_w2v import LambdaOverlapAdd_Chunkwise_Wav2Vec
from .overpaladd_chunk_spec_feat import LambdaOverlapAdd_Chunkwise_SpectralFeatures
from .oracle_methods import return_oracle_with_args
from .define_overlapadd import load_ola_func_with_args
